// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Name string `path:"name"`
}

type OrderReply struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Addr string `json:"addr"`
}
